export const freelancers = [
  {
    id: "1",
    name: "Amara Koné",
    title: "Designer UI/UX",
    location: "Abidjan, Côte d'Ivoire",
    avatar: "AK",
    avatarColor: "from-violet-400 to-purple-600",
    bio: "Je crée des interfaces qui convertissent. 5 ans d'expérience pour des startups africaines primées. Chaque pixel a une intention.",
    bioLong: "Passionnée par le design centré utilisateur, je travaille avec des startups et PME africaines pour créer des produits digitaux qui allient esthétique et performance. Mon processus : recherche utilisateur, wireframes, prototypes Figma, puis itération jusqu'à la perfection. J'ai collaboré avec des équipes à Lagos, Dakar et Nairobi.",
    skills: ["Figma", "Branding", "Motion", "Illustration", "Webflow", "Design System"],
    rating: 5.0,
    reviews: 142,
    price: "À partir de 15 000 FCFA",
    available: true,
    portfolio: [
      { color: "from-violet-100 to-purple-200", label: "App Fintech" },
      { color: "from-blue-100 to-indigo-200", label: "Dashboard" },
      { color: "from-pink-100 to-rose-200", label: "Branding" },
    ],
    services: [
      { name: "Identité visuelle complète", price: "80 000 FCFA", delay: "7 jours" },
      { name: "Design d'interface (5 écrans)", price: "45 000 FCFA", delay: "4 jours" },
      { name: "Logo + charte graphique", price: "25 000 FCFA", delay: "3 jours" },
    ],
    testimonials: [
      { author: "Marie T.", text: "Résultat bluffant, au-delà de mes attentes.", rating: 5 },
      { author: "Ibrahima S.", text: "Livraison rapide et très professionnelle.", rating: 5 },
    ],
  },
  {
    id: "2",
    name: "Segun Adeyemi",
    title: "Développeur Full-Stack",
    location: "Lagos, Nigeria",
    avatar: "SA",
    avatarColor: "from-emerald-400 to-teal-600",
    bio: "React, Next.js, Node. Je transforme vos idées en produits digitaux robustes. Livraison rapide, code propre, zéro compromis.",
    bioLong: "Développeur senior avec 7 ans d'expérience, je maîtrise l'ensemble du stack moderne : frontend React/Next.js, backend Node/Express, bases de données SQL et NoSQL, déploiement cloud. J'ai livré plus de 80 projets pour des clients au Nigeria, au Kenya et en Afrique du Sud.",
    skills: ["React", "Next.js", "Supabase", "Node.js", "TypeScript", "AWS"],
    rating: 4.9,
    reviews: 87,
    price: "À partir de 40 000 FCFA",
    available: true,
    portfolio: [
      { color: "from-emerald-100 to-teal-200", label: "E-commerce" },
      { color: "from-cyan-100 to-sky-200", label: "SaaS" },
      { color: "from-green-100 to-lime-200", label: "API REST" },
    ],
    services: [
      { name: "Landing page complète", price: "85 000 FCFA", delay: "5 jours" },
      { name: "Application web MVP", price: "250 000 FCFA", delay: "21 jours" },
      { name: "Intégration API / Backend", price: "60 000 FCFA", delay: "7 jours" },
    ],
    testimonials: [
      { author: "Chioma O.", text: "Mon app était prête en 3 semaines, parfaite.", rating: 5 },
      { author: "David K.", text: "Code impeccable, très bon communicant.", rating: 5 },
    ],
  },
  {
    id: "3",
    name: "Fatou Diallo",
    title: "Social Media Manager",
    location: "Dakar, Sénégal",
    avatar: "FD",
    avatarColor: "from-amber-400 to-orange-500",
    bio: "Votre marque mérite d'être vue. Je crée du contenu qui engage, des stratégies qui font grandir, des communautés qui restent.",
    bioLong: "Experte en growth marketing et community management, j'aide les marques africaines à bâtir une présence digitale forte. Stratégie de contenu, production de visuels, gestion de campagnes publicitaires Meta et TikTok, analyse des performances. 210 clients satisfaits en 4 ans.",
    skills: ["Instagram", "TikTok", "Copywriting", "Meta Ads", "Canva", "Analytics"],
    rating: 4.8,
    reviews: 210,
    price: "À partir de 10 000 FCFA",
    available: false,
    portfolio: [
      { color: "from-amber-100 to-orange-200", label: "Campagne" },
      { color: "from-yellow-100 to-amber-200", label: "Reels" },
      { color: "from-rose-100 to-pink-200", label: "Strategy" },
    ],
    services: [
      { name: "Pack réseaux sociaux (1 mois)", price: "45 000 FCFA", delay: "Continu" },
      { name: "Campagne publicité Meta", price: "30 000 FCFA", delay: "3 jours" },
      { name: "Audit + stratégie social media", price: "15 000 FCFA", delay: "2 jours" },
    ],
    testimonials: [
      { author: "Aïssatou B.", text: "+3000 abonnés en un mois, incroyable.", rating: 5 },
      { author: "Marc L.", text: "Notre engagement a triplé grâce à Fatou.", rating: 5 },
    ],
  },
  {
    id: "4",
    name: "Kwame Asante",
    title: "Développeur Mobile",
    location: "Accra, Ghana",
    avatar: "KA",
    avatarColor: "from-sky-400 to-blue-600",
    bio: "Flutter & React Native. Des apps mobiles natives, performantes, belles. De l'idée à l'App Store en un temps record.",
    bioLong: "Spécialiste mobile avec une expertise Flutter et React Native, je développe des applications cross-platform de qualité native. Mes apps sont disponibles sur l'App Store et le Play Store. Je gère tout : UX, développement, tests, soumission aux stores.",
    skills: ["Flutter", "Firebase", "iOS/Android", "React Native", "Dart", "App Store"],
    rating: 5.0,
    reviews: 63,
    price: "À partir de 60 000 FCFA",
    available: true,
    portfolio: [
      { color: "from-sky-100 to-blue-200", label: "App iOS" },
      { color: "from-indigo-100 to-violet-200", label: "App Android" },
      { color: "from-blue-100 to-cyan-200", label: "MVP" },
    ],
    services: [
      { name: "App mobile MVP (iOS + Android)", price: "300 000 FCFA", delay: "30 jours" },
      { name: "Écran / fonctionnalité Flutter", price: "40 000 FCFA", delay: "5 jours" },
      { name: "Publication App Store + Play Store", price: "25 000 FCFA", delay: "3 jours" },
    ],
    testimonials: [
      { author: "Yaw A.", text: "App livrée en avance, RAS sur la qualité.", rating: 5 },
      { author: "Nana O.", text: "Kwame est le meilleur dev mobile que j'ai eu.", rating: 5 },
    ],
  },
  {
    id: "5",
    name: "Aïcha Touré",
    title: "Rédactrice & Copywriter",
    location: "Bamako, Mali",
    avatar: "AT",
    avatarColor: "from-rose-400 to-pink-600",
    bio: "Les mots vendent. Je rédige des contenus SEO, landing pages et newsletters qui transforment les visiteurs en clients.",
    bioLong: "Copywriter et content strategist, je travaille pour des marques qui veulent que leurs mots aient de l'impact. SEO on-page, tunnels de vente, séquences email, articles de blog — chaque texte est pensé pour convertir. Bilingue français/anglais.",
    skills: ["SEO", "Blog", "Newsletter", "Copywriting", "Email Marketing", "WordPress"],
    rating: 4.9,
    reviews: 178,
    price: "À partir de 8 000 FCFA",
    available: true,
    portfolio: [
      { color: "from-rose-100 to-pink-200", label: "Articles SEO" },
      { color: "from-fuchsia-100 to-purple-200", label: "Landing Page" },
      { color: "from-pink-100 to-rose-200", label: "Newsletter" },
    ],
    services: [
      { name: "Article SEO (1500 mots)", price: "12 000 FCFA", delay: "2 jours" },
      { name: "Landing page complète", price: "35 000 FCFA", delay: "4 jours" },
      { name: "Séquence email (5 emails)", price: "25 000 FCFA", delay: "3 jours" },
    ],
    testimonials: [
      { author: "Sidy C.", text: "Mes articles sont en première page Google.", rating: 5 },
      { author: "Lamine D.", text: "Plume exceptionnelle, je recommande.", rating: 5 },
    ],
  },
];

export type Freelancer = typeof freelancers[0];

export function getFreelancer(id: string): Freelancer | undefined {
  return freelancers.find((f) => f.id === id);
}
